# Table of Contents
# -----------------

toc:
  - head: /index.html
    body: []

  - head: /basics/index.html
    body:
     - /basics/actions.html
     - /basics/routes.html
     - /basics/requests.html
     - /basics/results.html
     - /basics/failure.html

  - head: /json/index.html
    body:
     - /json/types.html
     - /json/writes.html
     - /json/reads.html
     - /json/formats.html
     - /json/custom.html
     - /json/oformats.html
     - /json/failure.html

  - head: /async/index.html
    body:
     - /async/futures.html
     - /async/executioncontexts.html
     - /async/actions.html
     - /async/failure.html
     - /async/ws.html

# Jekyll Configuration
# --------------------

url         : http://underscore.io

source      : src/pages
posts       : ../posts
layouts     : ../layouts
includes    : ../includes

destination : essential-play
plugins     : jekyll_plugins

keep_files  : [ 'css', 'js', 'images' ]

permalink   : /:categories/:year/:month/:day/:title

safe        : false
highlighter : true
markdown    : kramdown
markdown_ext: foo

kramdown:
  parse_block_html: true